# Generated by Django 4.2.20 on 2025-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('booking_count', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
