# Generated by Django 4.2.20 on 2025-03-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inventory.inventory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='member.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
